CREATE TABLE IF NOT EXISTS Country (
	id int4 PRIMARY KEY,
	name VARCHAR(256) UNIQUE
);

CREATE TABLE IF NOT EXISTS League (
	id int4 PRIMARY KEY,
	country_id int4,
	name TEXT UNIQUE
);


CREATE TABLE IF NOT EXISTS Player (
	id	int4 PRIMARY KEY,
	player_api_id	int4 UNIQUE,
	player_name	TEXT,
	player_fifa_api_id	int4 UNIQUE,
	birthday	TEXT,
	height	NUMERIC,
	weight	NUMERIC
);

CREATE TABLE IF NOT EXISTS Player_Attributes (
	id	int4 PRIMARY KEY,
	player_fifa_api_id	int4,
	player_api_id	int4,
	date	TEXT,
	overall_rating	int4,
	potential	int4,
	preferred_foot	TEXT,
	attacking_work_rate	TEXT,
	defensive_work_rate	TEXT,
	crossing	int4,
	finishing	int4,
	heading_accuracy	int4,
	short_passing	int4,
	volleys	int4,
	dribbling	int4,
	curve	int4,
	free_kick_accuracy	int4,
	long_passing	int4,
	ball_control	int4,
	acceleration	int4,
	sprint_speed	int4,
	agility	int4,
	reactions	int4,
	balance	int4,
	shot_power	int4,
	jumping	int4,
	stamina	int4,
	strength	int4,
	long_shots	int4,
	aggression	int4,
	interceptions	int4,
	positioning	int4,
	vision	int4,
	penalties	int4,
	marking	int4,
	standing_tackle	int4,
	sliding_tackle	int4,
	gk_diving	int4,
	gk_handling	int4,
	gk_kicking	int4,
	gk_positioning	int4,
	gk_reflexes	int4
);

CREATE TABLE IF NOT EXISTS Team (
	id	int4 PRIMARY KEY,
	team_api_id	int4 UNIQUE,
	team_fifa_api_id	int4,
	team_long_name	TEXT,
	team_short_name	TEXT
);

CREATE TABLE IF NOT EXISTS Team_Attributes (
	id	int4 PRIMARY KEY,
	team_fifa_api_id	int4,
	team_api_id	int4,
	date	TEXT,
	buildUpPlaySpeed	int4,
	buildUpPlaySpeedClass	TEXT,
	buildUpPlayDribbling	int4,
	buildUpPlayDribblingClass	TEXT,
	buildUpPlayPassing	int4,
	buildUpPlayPassingClass	TEXT,
	buildUpPlayPositioningClass	TEXT,
	chanceCreationPassing	int4,
	chanceCreationPassingClass	TEXT,
	chanceCreationCrossing	int4,
	chanceCreationCrossingClass	TEXT,
	chanceCreationShooting	int4,
	chanceCreationShootingClass	TEXT,
	chanceCreationPositioningClass	TEXT,
	defencePressure	int4,
	defencePressureClass	TEXT,
	defenceAggression	int4,
	defenceAggressionClass	TEXT,
	defenceTeamWidth	int4,
	defenceTeamWidthClass	TEXT,
	defenceDefenderLineClass	TEXT
);

CREATE TABLE IF NOT EXISTS Match (
	id	int4 PRIMARY KEY,
	country_id	int4,
	league_id	int4,
	season	TEXT,
	stage	int4,
	date	TEXT,
	match_api_id	int4 UNIQUE,
	home_team_api_id	int4,
	away_team_api_id	int4,
	home_team_goal	int4,
	away_team_goal	int4,
	home_player_X1	int4,
	home_player_X2	int4,
	home_player_X3	int4,
	home_player_X4	int4,
	home_player_X5	int4,
	home_player_X6	int4,
	home_player_X7	int4,
	home_player_X8	int4,
	home_player_X9	int4,
	home_player_X10	int4,
	home_player_X11	int4,
	away_player_X1	int4,
	away_player_X2	int4,
	away_player_X3	int4,
	away_player_X4	int4,
	away_player_X5	int4,
	away_player_X6	int4,
	away_player_X7	int4,
	away_player_X8	int4,
	away_player_X9	int4,
	away_player_X10	int4,
	away_player_X11	int4,
	home_player_Y1	int4,
	home_player_Y2	int4,
	home_player_Y3	int4,
	home_player_Y4	int4,
	home_player_Y5	int4,
	home_player_Y6	int4,
	home_player_Y7	int4,
	home_player_Y8	int4,
	home_player_Y9	int4,
	home_player_Y10	int4,
	home_player_Y11	int4,
	away_player_Y1	int4,
	away_player_Y2	int4,
	away_player_Y3	int4,
	away_player_Y4	int4,
	away_player_Y5	int4,
	away_player_Y6	int4,
	away_player_Y7	int4,
	away_player_Y8	int4,
	away_player_Y9	int4,
	away_player_Y10	int4,
	away_player_Y11	int4,
	home_player_1	int4,
	home_player_2	int4,
	home_player_3	int4,
	home_player_4	int4,
	home_player_5	int4,
	home_player_6	int4,
	home_player_7	int4,
	home_player_8	int4,
	home_player_9	int4,
	home_player_10	int4,
	home_player_11	int4,
	away_player_1	int4,
	away_player_2	int4,
	away_player_3	int4,
	away_player_4	int4,
	away_player_5	int4,
	away_player_6	int4,
	away_player_7	int4,
	away_player_8	int4,
	away_player_9	int4,
	away_player_10	int4,
	away_player_11	int4,
	goal	TEXT,
	shoton	TEXT,
	shotoff	TEXT,
	foulcommit	TEXT,
	card	TEXT,
	cross_stat	TEXT,
	corner	TEXT,
	possession	TEXT,
	B365H	NUMERIC,
	B365D	NUMERIC,
	B365A	NUMERIC,
	BWH	NUMERIC,
	BWD	NUMERIC,
	BWA	NUMERIC,
	IWH	NUMERIC,
	IWD	NUMERIC,
	IWA	NUMERIC,
	LBH	NUMERIC,
	LBD	NUMERIC,
	LBA	NUMERIC,
	PSH	NUMERIC,
	PSD	NUMERIC,
	PSA	NUMERIC,
	WHH	NUMERIC,
	WHD	NUMERIC,
	WHA	NUMERIC,
	SJH	NUMERIC,
	SJD	NUMERIC,
	SJA	NUMERIC,
	VCH	NUMERIC,
	VCD	NUMERIC,
	VCA	NUMERIC,
	GBH	NUMERIC,
	GBD	NUMERIC,
	GBA	NUMERIC,
	BSH	NUMERIC,
	BSD	NUMERIC,
	BSA	NUMERIC
);


CREATE TABLE IF NOT EXISTS Points (
	league_id int4,
	league_name TEXT,
    season TEXT,
  	table_position int4,
    team_name_stats TEXT,
    W int4,
    D int4,
    L int4,
    GF int4,
    GA int4,
    GD int4,
    cum_points NUMERIC 
);